name: Update notion databases

on: 
  - workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry export -f requirements.txt --output requirements.txt
          pip install -r requirements.txt
      - name: Execute
        env:
          NOTION_MARKER_NOTION_MOVIE_DATABASE_ID: ${{ secrets.NOTION_MARKER_NOTION_MOVIE_DATABASE_ID }}
          NOTION_MARKER_NOTION_TOKEN: ${{ secrets.NOTION_MARKER_NOTION_TOKEN }}
          NOTION_MARKER_TMDB_API_KEY: ${{ secrets.NOTION_MARKER_TMDB_API_KEY }}
        run: |
          python main.py